### ISSUE TITLE
Problem when testing ovs-dpdk

### ISSUE THREAD

**Issue by DucHoangManh** [intel/userspace-cni-network-plugin#63]
After creating pod, with following mount folder:
(I tried to set the shared-dir to ```/var/run/openvswitch/unique_directory``` but got the error ```Rename ERROR:... invalid cross-device link``` so, I use the default folder for testing purpose)
```yaml
 - mountPath: /vhu
      name: shared-dir
  volumes:
  - name: shared-dir
    hostPath:
      path: /var/run/openvswitch/
```
I see the socket files show up in ```/var/run/openvswitch/```, but when testing with testpmd, its always showing 0 statistic. I don't know how to fix this..
